line-length = 100
target-version = "py312"

[lint]
ignore = [
  "E501",
  "ANN401",
  "PLR0913",
  "PLR2004",
  "PLR0917",
  "PLR6301",
  "ANN002",
  "ERA001",
  "RUF100",
  "B903",
]
preview = true
select = [
  "E",
  "W",
  "C90",
  "F",
  "UP",
  "B",
  "SIM",
  "I",
  "N",
  "TCH",
  "ANN",
  "ASYNC",
  "A",
  "C4",
  "EM",
  "FA",
  "ICN",
  "G",
  "PIE",
  "T20",
  "ARG",
  "ERA",
  "LOG",
  "PL",
  "TRY",
  "RUF",
]

[lint.flake8-type-checking]
quote-annotations = true

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"test.py" = ["ALL"]
"migrations/*.py" = ["ALL"]

[lint.isort]
required-imports = ["from __future__ import annotations"]
split-on-trailing-comma = false

[format]
skip-magic-trailing-comma = true
